name: chat_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  # Dependencias

  http: ^0.12.2

  provider: ^4.3.3

  pull_to_refresh: ^1.6.4

  socket_io_client: ^0.9.12

  flutter_secure_storage: ^3.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
